name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install (core)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Smoke import
        run: |
          python - <<'PY'
          try:
              import hospops_forecast as m
              print("Imported OK, version:", getattr(m, "__version__", "unknown"))
          except Exception as e:
              print("IMPORT FAILED:", e)
              raise
          PY
