name: PY-MIN

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Show Python Version
        run: python -V
